### ISSUE TITLE
[Server Side Rendering] `fetch` is not defined, in fetch wrapper

### ISSUE THREAD

**Issue by ryancole** [nodkz/react-relay-network-layer#12]
I'm implementing server side rendering, with isomorphic-relay. I also use your react-relay-network-layer.

On the client, after going through a webpack build process during which I can bundle in `fetch` globally, react-relay-network-layer works great.

On the server, however, there is no webpack build process and there is no global `fetch` function. I'm seeing errors when trying to `renderToString`, on the server: `fetch` is not defined`.

I went and looked at the `RelayDefaultNetworkLayer` that ships with Relay, and they go ahead and explicitly `require("fetch")`. That `require` will work on the client just fine, assuming a webpack build process but it also enable server side rendering because `fetch` won't be global there.

https://github.com/facebook/relay/blob/master/src/network-layer/default/RelayDefaultNetworkLayer.js#L17

Do you think react-relay-network-layer's fetch wrapper should `require("fetch")`?

```
C:\Users\Ryan\Projects\league\node_modules\promise\lib\done.js:10
      throw err;
      ^

ReferenceError: fetch is not defined
    at C:\Users\Ryan\Projects\league\node_modules\react-relay-network-layer\lib\fetchWrapper.js:39:14
    at new Promise (C:\Users\Ryan\Projects\league\node_modules\core-js\modules\es6.promise.js:191:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (C:\Users\Ryan\Projects\league\node_modules\core-js\library\modules\_export.js:35:28)
    at fetchAfterAllWrappers (C:\Users\Ryan\Projects\league\node_modules\react-relay-network-layer\lib\fetchWrapper.js:37:12)
    at C:\Users\Ryan\Projects\league\node_modules\react-relay-network-layer\lib\middleware\auth.js:66:16
    at run (C:\Users\Ryan\Projects\league\node_modules\core-js\modules\es6.promise.js:87:22)
    at C:\Users\Ryan\Projects\league\node_modules\core-js\modules\es6.promise.js:100:28
    at flush (C:\Users\Ryan\Projects\league\node_modules\core-js\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by ryancole** [comment]
After looking at react-relay-network-layer code some more, I see that `fetch` is not even a project dependency. Is this an assumption that it'll be available globally, or is there something else that I'm not seeing that allows `fetch` to be used without being defined?

**Comment by nodkz** [comment]
In 1.2.0 (June 21, 2016) was removed  whatwg-fetch polyfill, due problem in React Native (issue #8).

If your client does not have fetch global method, you should include polyfill explicitly in you code:

```js
  import 'whatwg-fetch'; // for old browsers
  // or
  import 'node-fetch';  // for old node versions
  // or
  import 'fetch-everywhere'; // fresh isomorphic fetch polyfill, that supports all clients (not tested ;)
```

So you should explicitly import preferred `fetch` polifill in server.js.

**Comment by nodkz** [comment]
What version of nodejs you use, for my info?

Also about polifill I wrote in readme.md, so absence of fetch is desired solution.

**Comment by ryancole** [comment]
Currently on node `6.2.0`.

I'll try out `fetch-everywhere`.

**Comment by ryancole** [comment]
Alright. Adding `fetch-everywhere` seems to work. Sorry for not noticing this in the read me. :(

**Comment by nodkz** [comment]
No problem! 😉
