### ISSUE TITLE
graphql/batch should end response and not pass execution to next callback

### ISSUE THREAD

**Issue by genbit** [nodkz/react-relay-network-layer#13]
Hi, 

I found in the code, that after processing graphql batch, express middleware will just call next();

https://github.com/nodkz/react-relay-network-layer/blob/master/src/express-middleware/graphqlBatchHTTPWrapper.js#L43

It causes request to be processed again by standard graphql middleware, which leads to an error.

**Comment by nodkz** [comment]
Thanks!

I'll fix it in 2 days. I have a small vacation right now and answer from mobile to you.

**Comment by nodkz** [comment]
Fixed in 1.3.3
