### ISSUE TITLE
Need fetch to send cookies, need to pass option to fetch

### ISSUE THREAD

**Issue by ryancole** [nodkz/react-relay-network-layer#15]
In order to implement server side rendering, I've switched from local storage to cookies. Local storage does not work for server rendering because it's a pure JS API and in order for JS to run the page needs to be requested first, which once that has happened you're past the point of server rendering. So, since browsers send cookies natively, cookies are to be used for server rendering so that first request has the session token.

With that said, `fetch` does not send cookies by default. In order for `fetch` to send cookies, you need to pass in some [additional options](https://github.com/github/fetch#sending-cookies).

I need to pass the `credentials` option to `fetch`. Looking at your code, I can't quite tell how the `opts` are defined. Is there an existing way for me to set `credentials` for `fetch`? How do you suggest I go about doing this, whether it's a modification to this lib, or some additional network layer middleware, etc?

Thanks!

**Comment by nodkz** [comment]
Try `req.credentials`: make search  "example of the custom inline middleware" in the readme.md for example. I'm on mobile right now.

I'll be at work in hour. If you provide server implementation I will help you find better solution.

**Comment by ryancole** [comment]
Yea, based on my looking at the code, it looks like you pass all props from`req` into `fetch`, which probably is over kill. `req` has a ton of props. I'll try it out though and see what happens.

**Comment by nodkz** [comment]
In terms of middlewares `req = { url: fetch.url, ...fetch.opts }`. It's not an express' request object.
So basically `req = { url: '/graphql' }`, and you extends this object by `fetch options` direcly.

**Comment by nodkz** [comment]
Add a little bit more clarification to README.MD:

```js
  // example of the custom inline middleware
  next => req => {
    // `req` is an object with settings for `fetch` function. It's not an express request object.
    // Internally works following code:
    //    let { url, ...opts } = req;
    //    fetch(url, opts)
    // So `req` is a fetch options. And into this options, I added `url` prop, which will be extracted as shown above.
    // You have fully control under `fetch` via `req` object.
    
    req.headers['X-Request-ID'] = uuid.v4(); // add `X-Request-ID` to request headers
    req.credentials = 'same-origin'; // provide CORS policy to XHR request in fetch method
    return next(req);
  }
```

If you find typos, please correct my mistakes.

**Comment by ryancole** [comment]
Awesome, thanks!

**Comment by ryancole** [comment]
Hmm. This seems to be breaking Relay. When I use the following middleware ...

```js
function fetchOptionsMiddleware(next) {
  return (req) => {
    req.credentials = "include";
    return next(req);
  };
};
```

Something seems to break when I enable this middleware. Client-side `fetch` requests don't seem to include all queries or something. Relay complains about data not being fetched.

I'm still looking into it to see if I can figure out exactly what's breaking. Does anything here look wrong to you?

```js
import {RelayNetworkLayer, urlMiddleware} from "react-relay-network-layer";
import {GRAPHQL_ENDPOINT} from "../../../conf/server.config";

function fetchOptionsMiddleware(next) {
  return (req) => {
    req.credentials = "include";
    return next(req);
  };
};

export default new RelayNetworkLayer([
  urlMiddleware({
    url: GRAPHQL_ENDPOINT,
    batchUrl: `${GRAPHQL_ENDPOINT}/batch`
  }),
  fetchOptionsMiddleware
]);
```

**Comment by ryancole** [comment]
Hmm. I think the middleware function is fine, but I think the issue is with setting `credentials`. I can set other properties and nothing breaks, but if I set `credentials` it seems to break.

**Comment by ryancole** [comment]
I'm going to close this, actually. I think the error is something in my code somewhere. I can see that the requests now do include cookies, as expected. So, I do believe that your suggestion has indeed worked but I think the cookie is breaking my code somewhere else. Thanks!

**Comment by ryancole** [comment]
Yup. Ended up being an issue on my end. Server rendering was not using auth cookie while client ajax queries were, so relay was breaking due to a data discrepancy between the primed data and subsequent queries.

**Comment by nodkz** [comment]
Glad, that you crack it!

**Comment by Blackening999** [comment]
even with req.credentials = 'same-origin' I don't have cookies set :(
I'm using Koa does someone else experience the same issue?

```ctx.cookies.set(STORE_KEY, sid)```
it's just ignored ^^^

**Comment by nodkz** [comment]
Cookies are set by browser automatically. Network Layer should not set cookies, this is not its task.

So if you don't have cookies in the browser after fetch, then you incorrectly prepared your server.

Also take a look on fetch spec, it has not only `same-origin`, may be in your case need to use other policy.
