### ISSUE TITLE
Client is not batching requests

### ISSUE THREAD

**Issue by zuhair-naqvi** [nodkz/react-relay-network-layer#16]
Hey @nodkz 

I'm using react-relay-router that has 3 routes being rendered with different root queries for a single path, I noticed that sendQueries is called 3 times with with requests param only containing the specific  root query for each call instead of a single sendQueries call with all 3 requests.

here's what the network layer looks like.

```
export default new RelayNetworkLayer([
  urlMiddleware({
    url: (req) => env.GRAPHQL_ENDPOINT_SECURE,
    batchUrl: (req) => env.GRAPHQL_ENDPOINT_SECURE
  }),
  loggerMiddleware(),
  gqErrorsMiddleware(),
  deferMiddleware(),
  perfMiddleware(),
  retryMiddleware({
    fetchTimeout: 15000,
    retryDelays: (attempt) => Math.pow(2, attempt + 4) * 100, // or simple array [3200, 6400, 12800, 25600, 51200, 102400, 204800, 409600],
    forceRetry: (cb, delay) => {
      window.forceRelayRetry = cb;
      console.log('call `forceRelayRetry()` for immediately retry! Or wait ' + delay + ' ms.');
    },
    statusCodes: [500, 503, 504]
  }),
  homepassAuthMiddleware()
], { disableBatchQuery: false });
```

Any ideas why this is happening?

**Comment by zuhair-naqvi** [comment]
PS I'm using this in concert with https://github.com/eyston/relay-composite-network-layer

The exported RelayNetworkLayer is passed to relay-composite-network-layer - could this be causing query batching to fail?

**Comment by nodkz** [comment]
I think that `compositeNetworkLayer` spreads one `sendQueries` call obtained from Relay to multiple: https://github.com/eyston/relay-composite-network-layer/blob/master/src/execute/network.js#L14,L16

So you need to combine somehow this requests into one back, before touching `react-relay-network-layer` [better solution]. 
Or write some bufferMiddleware for `react-relay-network-layer`, which will gather requests some period of time and then combine it to batch query send to the server and resolve it back [very hard and tricky solution].
Or maybe fork `relay-composite-network-layer` and write your own custom network layer [may be the simplest solution in your case].

**Comment by zuhair-naqvi** [comment]
The buffer middleware sounds like the most robust as different schemas in composite network layer may be using different network layers. I'll let you know how this goes!

**Comment by nodkz** [comment]
You should get back relayRequestObject from `req.relayReqObj`, create array of them and pass to
`queriesBatch(relayRequestList, fetchWithMiddleware)`.

It too hacky, but should work.

PS. Ideally, I should rewrite all network layer from scratch. Some internal parts are too ugly and not clear for me already 😳.
