### ISSUE TITLE
express-graphql 0.5.4 doesn't work with react-relay-network-layer

### ISSUE THREAD

**Issue by genbit** [nodkz/react-relay-network-layer#19]
After upgrading to express-graphql 0.5.4, react-relay-network-layer cannot return data from original graphql queries, in another words - simply whole UI will be broken.

probably because they introduced small fix:

@chentsulin 
> Use end() to write final data (e01eb2e @chentsulin)

Will maybe look later into react-relay-network-layer code, but if owner can take a look it will be awesome

**Comment by nodkz** [comment]
Nice catch. Fixed in a couple of minutes.
Bumped 1.3.4.

Please check, how it works in your app.

**Comment by nodkz** [comment]
Step by step I'm rewriting own express implementation 😂

It will be cool if Lee accepted this PR: https://github.com/graphql/express-graphql/pull/100

**Comment by genbit** [comment]
@nodkz looks like it's working, thanks for quick fix!
