### ISSUE TITLE
tap into each retry

### ISSUE THREAD

**Issue by proProbe** [nodkz/react-relay-network-layer#22]
Hello!

I first must say thank you for an awesome library. It has solved many of our problems that we have and also enabled us to test out some of the deferred functionality that is coming.

I have a question about tapping into each retry. We currently have a loadingscreen that we would like to dynamically change after each retry. Basically it will display different messages and potentially write down a countdown until next retry. Is this possible with the current implementation of the library?

My current config looks like this:
```
const getCustomNetworkLayer = (jwt: string) => {
    return new RelayNetworkLayer([
        urlMiddleware({
            url: (req) => config.graphqlURL,
        }),
        retryMiddleware({
            fetchTimeout: 15000,
            retryDelays: [ 3000, 5000, 10000, 20000 ],
            statusCodes: [500, 503, 504],
        }),
        next => req => {
            req.headers["Authorization"] = `Bearer ${jwt}`;
            return next(req);
        },
    ], { disableBatchQuery: true });
};
```

Thanks again!

**Comment by nodkz** [comment]
Use `forceRetry` option in the `retryMiddleware`.

```js
...
retryMiddleware({
  fetchTimeout: 15000,
  retryDelays: [ 3000, 5000, 10000, 20000 ],
  statusCodes: [500, 503, 504],
  forceRetry: (callThisFunctionIfUserPressRetryButton, timeToNextAutoRetry) => {
    setToYourStateThatDataInTransition(
      callThisFunctionIfUserPressRetryButton, 
      timeToNextAutoRetry
    );
  }
}),
```
And **before** OR **after** `retryMiddleware` you should add such custom middleware:
```js
next => req => {
  return next(req).then(res => {
    setToYourStateThatItCanRemoveLoadingScreen();
    return res;
  });
}
```

Please test it and give me feedback, where is the right place for second custom middleware (when data is received). How I remember it should be placed before `retryMiddleware`.

**Comment by proProbe** [comment]
thanks @nodkz! Im out for the weekend but will try it out during next week and return with some feedback on how it goes

**Comment by proProbe** [comment]
@nodkz I realized that with our current structure, it is quite hard to actually try this out... so I was not able to test if **before** or **after** is correct.

**Comment by proProbe** [comment]
@nodkz related to this question. Is it possible to somehow tell the middleware to only retry on some queries and perhaps even cancel queries? I currently have queries based on people zooming on a map. Running around the map sends queries which, with slow internet, stacks tons of queries. Would love to somehow be able to cancel queries based on one of the queries succeeding.

**Comment by nodkz** [comment]
I have not a ready solution for you. But can give you some ideas, that may help to find a proper solution for your business logic:

1) Current/standard `fetch` implementation does not support request canceling. So you should find a proper module that supports it. Or write some fetch pool that sends requests in a serial and rejects first requests if their number become too much. 

2) You may write custom middleware which will catch some queries and pass them via custom fetch logic
```js
next => req => {
  if (req.relayReqObj.getQueryString().indexOf('some substring from query which indetifying zooming queries')) {
    // custom logic with fetching, retrying and aborting
    return promiseWithResponse; // it may be rejected, if you do not want keep many requests
  }
  // other queries via standard logic
  return next(req); 
}
```

3) Of course, better will be to keep this logic near app. And somehow use `Relay.Renderer` with `retry` callback. Take a close look on this [example](https://facebook.github.io/relay/docs/api-reference-relay-renderer.html#render-example).

PS. If you didn't find a solution, feel free to open a new issue with a detailed explanation of your problem. I'll add badges `question` and `help wanted`, maybe somebody can help you.
