### ISSUE TITLE
Refresh token executed multiple times, when one time should be enough 

### ISSUE THREAD

**Issue by alexxv** [nodkz/react-relay-network-layer#25]
Hey,

We have a scenario, where multiple concurrent requests receive HTTP 401, 
because authentication token is expired. Every one of those triggers a `refreshToken` flow, thus we have multiple refreshes concurrently.

I think it should there should be only one refreshToken promise running simultaneously, 

What do you think?

If you think it's worth adding, I'll be glad to submit a PR with this.
I've implemented this kind of solution for our app, it's very simple

Alex

**Comment by nodkz** [comment]
Cool. Will glad to accept your PR!

Cause client is one, token is also one, so only one refreshToken call will cover 99% of use cases.

**Comment by nodkz** [comment]
@alexxv if you have no time for PR, maybe you can share your code?

**Comment by alexxv** [comment]
@nodkz

**Comment by alexxv** [comment]
sorry, accidentally closed the issue

**Comment by alexxv** [comment]
@nodkz I've open a PR #32, take a look, lmk what you think

**Comment by nodkz** [comment]
Awesome. Super simple and useful solution. Thanks a lot!
