### ISSUE TITLE
batchUrl property of URL middleware is not passed req

### ISSUE THREAD

**Issue by chris-verclytte** [nodkz/react-relay-network-layer#36]
Hello,

I wonder why url property is  wrapped with req (https://github.com/nodkz/react-relay-network-layer/blob/master/src/middleware/url.js#L26) allowing for data being passed by another middleware through req but batchUrl is not.
My use case is that I am dynamically retrieving the api url with a middleware, and I would like both url and batchUrl to use the api url from req.

**Comment by nodkz** [comment]
`urlMiddleware` determines which type of query *single* or *batched* via `req.relayReqType === 'batch-query'` [see](https://github.com/nodkz/react-relay-network-layer/blob/master/src/middleware/url.js#L19-L26)  and passes to next middleware just `url` for fetching (supposing that all other middlewares do not care about url).

So if you want to create more complex logic, do not use `urlMiddleware` and write your own [inline middleware](https://github.com/nodkz/react-relay-network-layer#example-of-injecting-networklayer-with-middlewares-on-the-client-side) (find example with `next => req => {...}` in readme.md).

**Comment by chris-verclytte** [comment]
I agree with that but I am not sure we are talkin gabout the same thing.
I see this example in the documentation: 
```
urlMiddleware({
    url: (req) => '/graphql',
  }),
```

and thus would expect this code to work:
```
urlMiddleware({
    url: (req) => req.someProperty + '/graphql',
    batchUrl: (req) => req.someProperty + '/graphql/batch',
  }),
```

but it seems that batchUrl does not accept a function.

**Comment by nodkz** [comment]
```js
export default function urlMiddleware(opts = {}) {
  const urlOrThunk = opts.url || '/graphql';
  const batchUrlOrThunk = opts.batchUrl || '/graphql/batch';
  const fetchOpts = opts.opts;

  return next => req => {
    if (fetchOpts) {
      const { headers, ...otherOpts } = fetchOpts;
      Object.assign(req, otherOpts);
      if (headers) {
        Object.assign(req.headers, headers);
      }
    }

    let url;
    if (req.relayReqType === 'batch-query') {
      url = batchUrlOrThunk;
    } else {
      url = urlOrThunk;
    }

    req.url = isFunction(url) ? url(req) : url;

    return next(req);
  };
}
```
See carefully that `url` variable assigned to `batchUrlOrThunk` (opts.batchUrl) or `urlOrThunk` (opts.url) according to `req.relayReqType` value. And after that checking is `url` function or not. 

So it should work as you expected.

**Comment by chris-verclytte** [comment]
Ok got it, my error should came from another part then. I am closing this now as the behavior is the one expected.
