### ISSUE TITLE
authMiddleware stop working as of 2.0.0!

### ISSUE THREAD

**Issue by CarlRosell** [nodkz/react-relay-network-layer#42]
I noticed that the auth middleware just stopped working when updating to v2.0.0.

Here is the working config that was used before: 
```js
export const networkLayer = (store: Store<*, *>): RelayNetworkLayer =>
  new RelayNetworkLayer(
    [
      urlMiddleware({ url: graphQLURL }),
      authMiddleware({
        token: () => store.getState().auth.accessToken,
        tokenRefreshPromise: () => refreshToken(store.dispatch),
      }),
      next =>
        req => {
          req.headers['X-Stats-Timeout'] = statisticsTimeout;
          return next(req);
        },
    ],
    { disableBatchQuery: true },
  );
```
I then removed the batchQuery config as it was moved to another middleware but the auth middleware stopped working. It crashes on the, recently added, thrown error inside of the `fetchWithMiddlewares`-function https://github.com/nodkz/react-relay-network-layer/blob/master/src/fetchWithMiddleware.js#L25.

By throwing there the 401 error does not reach the 401 check inside of the `authMiddleweare`.

If you need more info just let me know 😄

**Comment by nodkz** [comment]
Thanks for reporting.
Please check new version. Should be published in a couple of minutes.

**Comment by CarlRosell** [comment]
That was fast 👍 Thanks
