### ISSUE TITLE
__dataID__ unknown field

### ISSUE THREAD

**Issue by atteia** [nodkz/react-relay-network-layer#43]
Hello

I'm using react-relay-network-layer and your [relayStore](https://gist.github.com/nodkz/03f28aaa1b66195b517ecf06e92487bf) with relay on web and when I post a mutation I got this error 

`message : "Variable "$input_0" got invalid value {"record":{"username":"admin","fullname":"ahmedAtia","phone":{"__dataID__":"client:-6654687382","phone":"055777098","kind":null,"localext":"123"},"address":{"__dataID__":"client:-6654687383","country":"SA","region":"SA","city":"Riyadh","street":"SA","knownmark":"sa"},"gender":"male"},"filter":{"_id":"58cfafd37b094855997ea271"},"clientMutationId":"0"}. In field "record": In field "phone": In field "__dataID__": Unknown field. In field "record": In field "address": In field "__dataID__": Unknown field."`

I did not use the batch for Relay because I have another error with it .

Could you help me to solve my error plz ?

**Comment by nodkz** [comment]
Just remove __dataID__ from objects which u pass to mutation. This is GraphQL validation error and it says that this field is not allowed in schema.

Can not provide more info, cause on vacation and only with mobile phone.

**Comment by atteia** [comment]
thanks for your help 
this is my [userEdit.js ](https://gist.github.com/atteia/1c747e012f2b54d4f77e59d312d9e111) and your [relayStore](https://gist.github.com/atteia/ca9c4a190903bf986f1db499cdf8cbbb)
and my [schema.js](https://gist.github.com/atteia/eadf5da2335b6ddfa2b6a8b2e6bbe3af)

now after deleting __dataID__ from object I got error 
`{"data":{"userUpdateOne":null},"errors":[{"message":"User validation failed","locations":[{"line":2,"column":3}],"path":["userUpdateOne"]}]}`

thanks for your help

**Comment by atteia** [comment]
thanks for your help 
this is my [userEdit.js ](https://gist.github.com/atteia/1c747e012f2b54d4f77e59d312d9e111) and your [relayStore](https://gist.github.com/atteia/ca9c4a190903bf986f1db499cdf8cbbb)
and my [schema.js](https://gist.github.com/atteia/eadf5da2335b6ddfa2b6a8b2e6bbe3af)

will I use delete Object.__dataID__ every time ? :(

**Comment by nodkz** [comment]
Nothing related to `react-relay-network-layer`.

Closing.
