### ISSUE TITLE
Uploading a file when using auth middleware fails

### ISSUE THREAD

**Issue by alexanderlamb** [nodkz/react-relay-network-layer#5]
Using the auth middleware while sending a mutation that includes a file fails.

It appears that the request headers property isn't defined before the Authorize header is being set in the auth middleware
Possible fix #4

**Comment by nodkz** [comment]
Thanks a lot!
New version 1.1.3 bumped to npm. 
Please test it, and let me know about results. ;)

PS. I'm not using files upload via mutations in my project. I decide to generate signed url for uploading directly to aws S3. And after uploading send just url via mutation.

**Comment by alexanderlamb** [comment]
@nodkz Seems to be working correctly now.
