### ISSUE TITLE
Relay Modern equivalent?

### ISSUE THREAD

**Issue by idris** [nodkz/react-relay-network-layer#50]
Is there an equivalent to this library for Relay Modern?  Or are there plans to adapt this library to Relay Modern?

**Comment by nodkz** [comment]
Now I'm refactoring our internal app with Flowtype. There are a lot of components and will take some time. After that, I want to migrate on Relay Modern.

I suppose that bump react-relay-network-layer@3.0.0 with supporting Relay Modern at the end of summer or in the beginning of autumn.

**Comment by toxsick** [comment]
Hi @nodkz,

I'm in the middle of refactoring an app to relay-modern and a modern compatible version would be great. Do you have a timeline for this right now?

Thank you for this great library. Helps a lot.

Hannes

**Comment by nodkz** [comment]
Can not guarantee that it happens in this month. But right now I'm migrating on moder with my demo app (https://github.com/nodkz/relay-northwind-app/commits/compat). And next will be our internal project where is used react-relay-network-layer. So i'm in progress to adopt react-relay-network-layer for relay-modern. I hope that it will be done in the end of this or next month.

Thanks for patience.

**Comment by idris** [comment]
@toxsick you may want to check out Apollo Link, which is compatible with Relay Modern: https://github.com/apollographql/apollo-link

**Comment by nodkz** [comment]
Opened new branch [modern](https://github.com/nodkz/react-relay-network-layer/commits/modern), I suppose till the end of next week all will be done.

**Comment by nodkz** [comment]
New package https://github.com/nodkz/react-relay-network-modern available on npm.
Please try it for Relay Modern.
