### ISSUE TITLE
Token not refreshing after user logs out and login again with different user.

### ISSUE THREAD

**Issue by softglance** [nodkz/react-relay-network-layer#53]
Below is the code implemented. It works for a single user. when user login is switched the token is not getting refreshed for the new token received from server. . 

On server side:
```js
networkLayer = !isBrowser() ? new Relay.DefaultNetworkLayer(GRAPHQL_URL,  {
      headers: {
        Authorization: store.get('jwt_token') ,
      },
      credentials: 'same-origin', 
    }
  ) : null;
```

On client side: 

```js
environment.injectNetworkLayer(new Relay.DefaultNetworkLayer(CLIENT_GRAPHQL_URL, { 
      headers: {
        Authorization: store.get('jwt_token') ,
      },
      credentials: 'same-origin',
     }));
```

On logout: 
```js
store.clearAll();
```

I also tried using react-relay-network-layer but facing same issue.

**Comment by nodkz** [comment]
Did you use `authMiddleware` with `react-relay-network-layer`?
This middleware will take a token from the store for every request.
```js
authMiddleware({
    token: () => store.get('jwt'),
    tokenRefreshPromise: (req) => {
      console.log('[client.js] resolve token refresh', req);
      return fetch('/jwt/refresh')
        .then(res => res.json())
        .then(json => {
          const token = json.token;
          store.set('jwt', token);
          return token;
        })
        .catch(err => console.log('[client.js] ERROR can not refresh token', err));
    },
  }),
```

**Comment by softglance** [comment]
Thanks! It works, now the token is getting refreshed.  After I login the old data from the relay store is loading.  I tried using the this.props.relay.forceFectch()  but still not getting the new data of logged in user.

**Comment by nodkz** [comment]
I such case you should create a new Relay Environment and replace old one in Relay.Renderer. (parent component just replace props `environment` by new instance)


https://facebook.github.io/relay/docs/api-reference-relay-renderer.html

**Comment by softglance** [comment]
after login I tried setting environment but with no luck.

this.context.relay.environment = new Relay.DefaultNetworkLayer('/graphql', { 
                  headers: relayStoreHeader,
                  credentials: 'same-origin',
                 });

**Comment by softglance** [comment]
The above comment was useful. Thanks!
