### ISSUE TITLE
regeneratorRuntime not defined in lib/fetchWithMiddleware.js

### ISSUE THREAD

**Issue by hannesj** [nodkz/react-relay-network-layer#54]
Currently the library crashes when trying to load it as `regeneratorRuntime` is not defined in `lib/fetchWithMiddleware.js`.

**Comment by nodkz** [comment]
It happens cause I upgrade a code with async/await syntax and now it starts to require regenerator runtime ((( It's sad.

So please use the previous version. Or temporary use such code:
```js
import 'regenerator-runtime/runtime';
import { RelayNetworkLayer } from 'react-relay-network-modern';
```

For fixing this problem needs to convert async/await syntax back to Promises

**Comment by nodkz** [comment]
I reverted async/await back to Promises, so new version should work without `regenerator-runtime`.

Thanks for reporting!
