### ISSUE TITLE
Batching: make query id optional

### ISSUE THREAD

**Issue by janmeier** [nodkz/react-relay-network-layer#55]
I'm trying to make the batching network layer work together with apollo-server-express. I'm using apollo-server instead of graphql-express + the middleware from this module, because it supports query and field tracing.

The batch middleware depends on an id for each batched query to connect requests and responses. However, apollo-server does not pass this id back. This actually turns out to be in line with the graphql spec:

> To ensure future changes to the protocol do not break existing servers and clients, the top level response map must not contain any entries other than the three described above. [data, errors, and extensions]
http://facebook.github.io/graphql/draft/#sec-Response-Format

However, the spec also defines that JSON serialization is ordered: 
> Since the result of evaluating a selection set is ordered, the JSON object serialized should preserve this order by writing the object properties in the same order as those fields were requested as defined by query execution.
http://facebook.github.io/graphql/draft/#sec-JSON-Serialization

So it should be possible to correlate responses to requests without relying on ids. A solution could be to make the ID optional, and fall back to query index when there is no id.

I can implement this change if you think it sounds good, but I would like to get some feedback first.

**Comment by nodkz** [comment]
Will be great! 👍

Do it as a fallback if sub-responses do not contain `id`
- check that req/res has the same length (otherwise throw an error).
- and switch to ordered correlation.

PS. Try to not break old behavior.
Thanks.
