### ISSUE TITLE
Use fetch-everywhere

### ISSUE THREAD

**Issue by roman01la** [nodkz/react-relay-network-layer#8]
Hello. I'd like to use this module in React Native. But it's not possible at the moment, because of [`whatwg-fetch`](https://github.com/nodkz/react-relay-network-layer/blob/master/src/fetchWrapper.js#L3). I've replaced it with [fetch-everywhere](https://github.com/lucasfeliciano/fetch-everywhere) in [my fork](https://github.com/roman01la/react-relay-network-layer/commit/2d87fdced28c54bb26fccc6b4dcc58ae4365ae12). The module [supports all kind of environments](https://github.com/lucasfeliciano/fetch-everywhere#suported-environments). I could prepare a PR, what do you think?

**Comment by nodkz** [comment]
`fetch-everywhere` is not popular, may be exists more common used alternatives?
Anyway `whatwg-fetch` should die ;)

**Comment by nodkz** [comment]
Please try this popular module https://www.npmjs.com/package/isomorphic-fetch

**Comment by roman01la** [comment]
@nodkz Unfortunately author of that library rejected to adapt it to React Native. It only works in browser and Node. That's why [`fetch-everywhere`](https://github.com/matthew-andrews/isomorphic-fetch/issues/59#issuecomment-226233921) was created.

> fetch-everywhere is not popular, may be exists more common used alternatives?

I guess `fetch-everywhere` is not popular because there are not much projects which use React and Relay and share fetching logic between mobile and browser platforms. But since Relay is specific to React, I think it would be fair to include React Native support.

**Comment by nodkz** [comment]
Good. Open PR please with `fetch-everywhere`. I'll test it on my project, and if all ok I'll bump new version today. 

Thanks!!!

**Comment by edvinerikson** [comment]
Isn't it better to let the user provide their own polyfill if they need it?

**Comment by nodkz** [comment]
@edvinerikson just remove `import 'whatwg-fetch';`? Good idea!

For browser `whatwg-fetch`
For node (server-side rendering) `node-fetch`
And what people use for react-native - ???

Needs for readme.

**Comment by roman01la** [comment]
That's great idea! React Native already includes fetch polyfill.

**Comment by nodkz** [comment]
bumped 1.2.0

**Comment by edvinerikson** [comment]
@nodkz exactly, this is what Relay does with the default network layer.
